name: google_mlkit_subject_segmentation
description:  Flutter plugin to use Google's ML Kit Selfie Segmentation API to easily separate the background from users within a scene and focus on what matters.
version: 0.0.1
homepage: https://github.com/flutter-ml/google_ml_kit_flutter

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

  plugin:
    platforms:
      android:
        package: com.google_mlkit_subject_segmentation
        pluginClass: GoogleMlKitSubjectSegmentationPlugin
      ios:
        pluginClass: GoogleMlKitSubjectSegmentationPlugin
