name: google_mlkit_barcode_scanning
description: A Flutter plugin to use Google's ML Kit Barcode Scanning to read data encoded using most standard barcode formats.
version: 0.12.1
homepage: https://github.com/flutter-ml/google_ml_kit_flutter
repository: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_barcode_scanning

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_barcode_scanning
        pluginClass: GoogleMlKitBarcodeScanningPlugin
      ios:
        pluginClass: GoogleMlKitBarcodeScanningPlugin
