name: google_mlkit_barcode_scanning
description: A Flutter plugin to use Google's ML Kit Barcode Scanning to read data encoded using most standard barcode formats.
version: 0.4.0
homepage: https://github.com/bharat-biradar/Google-Ml-Kit-plugin

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.2.0
#    path: ../google_mlkit_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_barcode_scanning
        pluginClass: GoogleMlKitBarcodeScanningPlugin
      ios:
        pluginClass: GoogleMlKitBarcodeScanningPlugin
