include: ../analysis_options.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
