// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.google_mlkit_translation;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Pigeon {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class TranslateRequest {
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    private @NonNull String text;

    public @NonNull String getText() {
      return text;
    }

    public void setText(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"text\" is null.");
      }
      this.text = setterArg;
    }

    private @NonNull String sourceLanguage;

    public @NonNull String getSourceLanguage() {
      return sourceLanguage;
    }

    public void setSourceLanguage(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sourceLanguage\" is null.");
      }
      this.sourceLanguage = setterArg;
    }

    private @NonNull String targetLanguage;

    public @NonNull String getTargetLanguage() {
      return targetLanguage;
    }

    public void setTargetLanguage(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"targetLanguage\" is null.");
      }
      this.targetLanguage = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    TranslateRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      TranslateRequest that = (TranslateRequest) o;
      return id.equals(that.id) && text.equals(that.text) && sourceLanguage.equals(that.sourceLanguage) && targetLanguage.equals(that.targetLanguage);
    }

    @Override
    public int hashCode() {
      return Objects.hash(id, text, sourceLanguage, targetLanguage);
    }

    public static final class Builder {

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      private @Nullable String text;

      @CanIgnoreReturnValue
      public @NonNull Builder setText(@NonNull String setterArg) {
        this.text = setterArg;
        return this;
      }

      private @Nullable String sourceLanguage;

      @CanIgnoreReturnValue
      public @NonNull Builder setSourceLanguage(@NonNull String setterArg) {
        this.sourceLanguage = setterArg;
        return this;
      }

      private @Nullable String targetLanguage;

      @CanIgnoreReturnValue
      public @NonNull Builder setTargetLanguage(@NonNull String setterArg) {
        this.targetLanguage = setterArg;
        return this;
      }

      public @NonNull TranslateRequest build() {
        TranslateRequest pigeonReturn = new TranslateRequest();
        pigeonReturn.setId(id);
        pigeonReturn.setText(text);
        pigeonReturn.setSourceLanguage(sourceLanguage);
        pigeonReturn.setTargetLanguage(targetLanguage);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(id);
      toListResult.add(text);
      toListResult.add(sourceLanguage);
      toListResult.add(targetLanguage);
      return toListResult;
    }

    static @NonNull TranslateRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      TranslateRequest pigeonResult = new TranslateRequest();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((String) id);
      Object text = pigeonVar_list.get(1);
      pigeonResult.setText((String) text);
      Object sourceLanguage = pigeonVar_list.get(2);
      pigeonResult.setSourceLanguage((String) sourceLanguage);
      Object targetLanguage = pigeonVar_list.get(3);
      pigeonResult.setTargetLanguage((String) targetLanguage);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class CloseTranslatorRequest {
    private @NonNull String id;

    public @NonNull String getId() {
      return id;
    }

    public void setId(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"id\" is null.");
      }
      this.id = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    CloseTranslatorRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      CloseTranslatorRequest that = (CloseTranslatorRequest) o;
      return id.equals(that.id);
    }

    @Override
    public int hashCode() {
      return Objects.hash(id);
    }

    public static final class Builder {

      private @Nullable String id;

      @CanIgnoreReturnValue
      public @NonNull Builder setId(@NonNull String setterArg) {
        this.id = setterArg;
        return this;
      }

      public @NonNull CloseTranslatorRequest build() {
        CloseTranslatorRequest pigeonReturn = new CloseTranslatorRequest();
        pigeonReturn.setId(id);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(1);
      toListResult.add(id);
      return toListResult;
    }

    static @NonNull CloseTranslatorRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      CloseTranslatorRequest pigeonResult = new CloseTranslatorRequest();
      Object id = pigeonVar_list.get(0);
      pigeonResult.setId((String) id);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ModelManagementRequest {
    private @NonNull String model;

    public @NonNull String getModel() {
      return model;
    }

    public void setModel(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"model\" is null.");
      }
      this.model = setterArg;
    }

    private @NonNull String task;

    public @NonNull String getTask() {
      return task;
    }

    public void setTask(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"task\" is null.");
      }
      this.task = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ModelManagementRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ModelManagementRequest that = (ModelManagementRequest) o;
      return model.equals(that.model) && task.equals(that.task);
    }

    @Override
    public int hashCode() {
      return Objects.hash(model, task);
    }

    public static final class Builder {

      private @Nullable String model;

      @CanIgnoreReturnValue
      public @NonNull Builder setModel(@NonNull String setterArg) {
        this.model = setterArg;
        return this;
      }

      private @Nullable String task;

      @CanIgnoreReturnValue
      public @NonNull Builder setTask(@NonNull String setterArg) {
        this.task = setterArg;
        return this;
      }

      public @NonNull ModelManagementRequest build() {
        ModelManagementRequest pigeonReturn = new ModelManagementRequest();
        pigeonReturn.setModel(model);
        pigeonReturn.setTask(task);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(model);
      toListResult.add(task);
      return toListResult;
    }

    static @NonNull ModelManagementRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ModelManagementRequest pigeonResult = new ModelManagementRequest();
      Object model = pigeonVar_list.get(0);
      pigeonResult.setModel((String) model);
      Object task = pigeonVar_list.get(1);
      pigeonResult.setTask((String) task);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ModelManagementResponse {
    private @NonNull Boolean success;

    public @NonNull Boolean getSuccess() {
      return success;
    }

    public void setSuccess(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"success\" is null.");
      }
      this.success = setterArg;
    }

    private @Nullable String message;

    public @Nullable String getMessage() {
      return message;
    }

    public void setMessage(@Nullable String setterArg) {
      this.message = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ModelManagementResponse() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ModelManagementResponse that = (ModelManagementResponse) o;
      return success.equals(that.success) && Objects.equals(message, that.message);
    }

    @Override
    public int hashCode() {
      return Objects.hash(success, message);
    }

    public static final class Builder {

      private @Nullable Boolean success;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccess(@NonNull Boolean setterArg) {
        this.success = setterArg;
        return this;
      }

      private @Nullable String message;

      @CanIgnoreReturnValue
      public @NonNull Builder setMessage(@Nullable String setterArg) {
        this.message = setterArg;
        return this;
      }

      public @NonNull ModelManagementResponse build() {
        ModelManagementResponse pigeonReturn = new ModelManagementResponse();
        pigeonReturn.setSuccess(success);
        pigeonReturn.setMessage(message);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(success);
      toListResult.add(message);
      return toListResult;
    }

    static @NonNull ModelManagementResponse fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ModelManagementResponse pigeonResult = new ModelManagementResponse();
      Object success = pigeonVar_list.get(0);
      pigeonResult.setSuccess((Boolean) success);
      Object message = pigeonVar_list.get(1);
      pigeonResult.setMessage((String) message);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return TranslateRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 130:
          return CloseTranslatorRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return ModelManagementRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return ModelManagementResponse.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof TranslateRequest) {
        stream.write(129);
        writeValue(stream, ((TranslateRequest) value).toList());
      } else if (value instanceof CloseTranslatorRequest) {
        stream.write(130);
        writeValue(stream, ((CloseTranslatorRequest) value).toList());
      } else if (value instanceof ModelManagementRequest) {
        stream.write(131);
        writeValue(stream, ((ModelManagementRequest) value).toList());
      } else if (value instanceof ModelManagementResponse) {
        stream.write(132);
        writeValue(stream, ((ModelManagementResponse) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface OnDeviceTranslatorApi {

    void translateText(@NonNull TranslateRequest request, @NonNull Result<String> result);

    void closeTranslator(@NonNull CloseTranslatorRequest request);

    void manageModel(@NonNull ModelManagementRequest request, @NonNull Result<ModelManagementResponse> result);

    /** The codec used by OnDeviceTranslatorApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `OnDeviceTranslatorApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable OnDeviceTranslatorApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable OnDeviceTranslatorApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_translation.OnDeviceTranslatorApi.translateText" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                TranslateRequest requestArg = (TranslateRequest) args.get(0);
                Result<String> resultCallback =
                    new Result<String>() {
                      public void success(String result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.translateText(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_translation.OnDeviceTranslatorApi.closeTranslator" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                CloseTranslatorRequest requestArg = (CloseTranslatorRequest) args.get(0);
                try {
                  api.closeTranslator(requestArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_translation.OnDeviceTranslatorApi.manageModel" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ModelManagementRequest requestArg = (ModelManagementRequest) args.get(0);
                Result<ModelManagementResponse> resultCallback =
                    new Result<ModelManagementResponse>() {
                      public void success(ModelManagementResponse result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.manageModel(requestArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
