// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

@import Foundation;

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class TranslateRequest;
@class CloseTranslatorRequest;
@class ModelManagementRequest;
@class ModelManagementResponse;

@interface TranslateRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    text:(NSString *)text
    sourceLanguage:(NSString *)sourceLanguage
    targetLanguage:(NSString *)targetLanguage;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * text;
@property(nonatomic, copy) NSString * sourceLanguage;
@property(nonatomic, copy) NSString * targetLanguage;
@end

@interface CloseTranslatorRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id;
@property(nonatomic, copy) NSString * id;
@end

@interface ModelManagementRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithModel:(NSString *)model
    task:(NSString *)task;
@property(nonatomic, copy) NSString * model;
@property(nonatomic, copy) NSString * task;
@end

@interface ModelManagementResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSuccess:(BOOL )success
    message:(nullable NSString *)message;
@property(nonatomic, assign) BOOL  success;
@property(nonatomic, copy, nullable) NSString * message;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void);

@protocol OnDeviceTranslatorApi
- (void)translateTextRequest:(TranslateRequest *)request completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)closeTranslatorRequest:(CloseTranslatorRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)manageModelRequest:(ModelManagementRequest *)request completion:(void (^)(ModelManagementResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpOnDeviceTranslatorApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<OnDeviceTranslatorApi> *_Nullable api);

extern void SetUpOnDeviceTranslatorApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<OnDeviceTranslatorApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
