// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Pigeon.h"

#if TARGET_OS_OSX
@import FlutterMacOS;
#else
@import Flutter;
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface TranslateRequest ()
+ (TranslateRequest *)fromList:(NSArray<id> *)list;
+ (nullable TranslateRequest *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CloseTranslatorRequest ()
+ (CloseTranslatorRequest *)fromList:(NSArray<id> *)list;
+ (nullable CloseTranslatorRequest *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ModelManagementRequest ()
+ (ModelManagementRequest *)fromList:(NSArray<id> *)list;
+ (nullable ModelManagementRequest *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface ModelManagementResponse ()
+ (ModelManagementResponse *)fromList:(NSArray<id> *)list;
+ (nullable ModelManagementResponse *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation TranslateRequest
+ (instancetype)makeWithId:(NSString *)id
    text:(NSString *)text
    sourceLanguage:(NSString *)sourceLanguage
    targetLanguage:(NSString *)targetLanguage {
  TranslateRequest* pigeonResult = [[TranslateRequest alloc] init];
  pigeonResult.id = id;
  pigeonResult.text = text;
  pigeonResult.sourceLanguage = sourceLanguage;
  pigeonResult.targetLanguage = targetLanguage;
  return pigeonResult;
}
+ (TranslateRequest *)fromList:(NSArray<id> *)list {
  TranslateRequest *pigeonResult = [[TranslateRequest alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.text = GetNullableObjectAtIndex(list, 1);
  pigeonResult.sourceLanguage = GetNullableObjectAtIndex(list, 2);
  pigeonResult.targetLanguage = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable TranslateRequest *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [TranslateRequest fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.id ?: [NSNull null],
    self.text ?: [NSNull null],
    self.sourceLanguage ?: [NSNull null],
    self.targetLanguage ?: [NSNull null],
  ];
}
@end

@implementation CloseTranslatorRequest
+ (instancetype)makeWithId:(NSString *)id {
  CloseTranslatorRequest* pigeonResult = [[CloseTranslatorRequest alloc] init];
  pigeonResult.id = id;
  return pigeonResult;
}
+ (CloseTranslatorRequest *)fromList:(NSArray<id> *)list {
  CloseTranslatorRequest *pigeonResult = [[CloseTranslatorRequest alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable CloseTranslatorRequest *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CloseTranslatorRequest fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.id ?: [NSNull null],
  ];
}
@end

@implementation ModelManagementRequest
+ (instancetype)makeWithModel:(NSString *)model
    task:(NSString *)task {
  ModelManagementRequest* pigeonResult = [[ModelManagementRequest alloc] init];
  pigeonResult.model = model;
  pigeonResult.task = task;
  return pigeonResult;
}
+ (ModelManagementRequest *)fromList:(NSArray<id> *)list {
  ModelManagementRequest *pigeonResult = [[ModelManagementRequest alloc] init];
  pigeonResult.model = GetNullableObjectAtIndex(list, 0);
  pigeonResult.task = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable ModelManagementRequest *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ModelManagementRequest fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.model ?: [NSNull null],
    self.task ?: [NSNull null],
  ];
}
@end

@implementation ModelManagementResponse
+ (instancetype)makeWithSuccess:(BOOL )success
    message:(nullable NSString *)message {
  ModelManagementResponse* pigeonResult = [[ModelManagementResponse alloc] init];
  pigeonResult.success = success;
  pigeonResult.message = message;
  return pigeonResult;
}
+ (ModelManagementResponse *)fromList:(NSArray<id> *)list {
  ModelManagementResponse *pigeonResult = [[ModelManagementResponse alloc] init];
  pigeonResult.success = [GetNullableObjectAtIndex(list, 0) boolValue];
  pigeonResult.message = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable ModelManagementResponse *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [ModelManagementResponse fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.success),
    self.message ?: [NSNull null],
  ];
}
@end

@interface nullPigeonPigeonCodecReader : FlutterStandardReader
@end
@implementation nullPigeonPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: 
      return [TranslateRequest fromList:[self readValue]];
    case 130: 
      return [CloseTranslatorRequest fromList:[self readValue]];
    case 131: 
      return [ModelManagementRequest fromList:[self readValue]];
    case 132: 
      return [ModelManagementResponse fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullPigeonPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullPigeonPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[TranslateRequest class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CloseTranslatorRequest class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ModelManagementRequest class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ModelManagementResponse class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullPigeonPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullPigeonPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullPigeonPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullPigeonPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullPigeonPigeonCodecReaderWriter *readerWriter = [[nullPigeonPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpOnDeviceTranslatorApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<OnDeviceTranslatorApi> *api) {
  SetUpOnDeviceTranslatorApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpOnDeviceTranslatorApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<OnDeviceTranslatorApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_translation.OnDeviceTranslatorApi.translateText", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(translateTextRequest:completion:)], @"OnDeviceTranslatorApi api (%@) doesn't respond to @selector(translateTextRequest:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        TranslateRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        [api translateTextRequest:arg_request completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_translation.OnDeviceTranslatorApi.closeTranslator", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(closeTranslatorRequest:error:)], @"OnDeviceTranslatorApi api (%@) doesn't respond to @selector(closeTranslatorRequest:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CloseTranslatorRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api closeTranslatorRequest:arg_request error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_translation.OnDeviceTranslatorApi.manageModel", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetPigeonCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(manageModelRequest:completion:)], @"OnDeviceTranslatorApi api (%@) doesn't respond to @selector(manageModelRequest:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        ModelManagementRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        [api manageModelRequest:arg_request completion:^(ModelManagementResponse *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
